language: go
sudo: required

go:
  - 1.8
  - 1.9
  - 1.10

env:
    - GO15VENDOREXPERIMENT="1"

before_install:
    - go get github.com/mattn/goveralls
    - Project=apollosdk

install:
    - go get github.com/cihub/seelog
    - go get github.com/coocood/freecache

script:
    - go build -o "$Project"